# Generated by Django 4.0.4 on 2022-04-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='post_id',
        ),
    ]
