# Generated by Django 4.0.4 on 2022-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0002_rename_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_id',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
